# Generated by Django 3.2.6 on 2021-08-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210825_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_Main_Img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='subject',
        ),
    ]
