# Generated by Django 3.2.6 on 2021-08-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_project_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='subject',
            new_name='name',
        ),
    ]
