# Generated by Django 3.2.6 on 2021-08-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_rename_subject_project_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
