# Generated by Django 3.2.6 on 2021-09-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='details',
            field=models.TextField(default='n/a', max_length=300),
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='Zambezi.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
