# Generated by Django 3.2.6 on 2021-09-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20210901_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='Zambezi.png', upload_to='images/'),
        ),
    ]
