# Generated by Django 3.2.6 on 2021-09-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.CharField(default='image', max_length=500),
        ),
    ]
